#!/usr/bin/env bash

make CROSS="$DEVKITARM/bin/arm-none-eabi-" HOST_CC="gcc -m32" TARGET_CFLAGS="-mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft" TARGET_SYS=Other TARGET_LDFLAGS="-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -specs=3dsx.specs -g -L $DEVKITPRO/libctru/lib -lctru -lm"
